version: '3.1'
services:

    aerolinker_core:
        image: nkotyuha/aerolinker_core:latest
        container_name: 'aerolinker_core'
        restart: on-failure
        networks:
            - back
        ports:
            - "5050:5050"
        environment:
            ASPNETCORE_ENVIRONMENT: 'Production'
        env_file:
            - /etc/environment

    aerolinker_frontend:
        depends_on:
            - aerolinker_core
            - aerolinker_notifier
        image: nkotyuha/aerolinker_frontend:latest
        container_name: 'aerolinker_frontend'
        restart: on-failure
        networks:
            - back
            - front
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
networks:
    back:
        driver: bridge
    front:
        driver: bridge
