version: '3.1'
services:
  aerolinker_core:
    build:
      context: ./backend
      dockerfile: ./AeroLinker.Core/Dockerfile
      args:
        - PROJECT_PORT=5050
    container_name: 'aerolinker_core'
    restart: on-failure
    ports:
        - "5050:5050"
    volumes:
        - logs:/app/Logs
    networks:
        - back
    environment:
        ASPNETCORE_ENVIRONMENT: 'Development'
        ConnectionStrings__AeroLinkerCoreDBConnection: 'Server=sql_server;Database=AeroLinkerCoreDB;User ID=SA;Password=MySecretPassword!'

  aerolinker_client:
    depends_on:
        - aerolinker_core
        - aerolinker_notifier
    build:
        context: ./frontend
        dockerfile: Dockerfile.dev
    container_name: 'aerolinker_frontend'
    restart: on-failure
    ports:
        - "4200:80"
    networks:
        - back
        - front

networks:
    back:
        driver: bridge
    front:
        driver: bridge

volumes:
    logs: